[package]
name = "qubes-shared-folders"
edition = "2021"
version = "0.0.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "qfsd"
path = "src/main.rs"

[dependencies]
p9 = { path = "p9" }
